.PHONY: clean All

All:
	@echo "----------Building project:[ rtp - Debug ]----------"
	@cd "rtp" && "$(MAKE)" -f  "rtp.mk"
clean:
	@echo "----------Cleaning project:[ rtp - Debug ]----------"
	@cd "rtp" && "$(MAKE)" -f  "rtp.mk" clean
